.TH unitex 1 "29 august 2022" "version 1.0" "Commands Manual"
.SH NAME
.B unitex
-- UniTeX is a collection of scientific oriented and minimalistic LaTeX templates suitable for many assignement types.
.SH SYNOPSIS
.B unitex
[\fB\-h\fR \fIHELP\fR]
[\fB\-v\fR \fIVERSION\fR]
[\fB\-b\fR \fIBUILD\fR]
[\fB\-d\fR \fIDIRECTORY\fR]
.SH DESCRIPTION
.B unitex
Uses latexmk LaTeX compiler to generate pre-built a pdf file from
pre-built templates defined in UniTeX folder inside
/usr/local/share/UniTeX/ folder.

NOTE: Most features need external tools such as latexmk that fully automates LaTeX document generation.
.SH OPTIONS
.TP
.B -h
Displays usage.
.TP
.B -v
Displays user's current version of UniTeX.
.TP
.B -b
Tells UniTeX to build chosen template using latexmk compiler.

(EX: classic, article, homework)
.TP
.B -d
Specifies path to building directory.

.SH EXAMPLES
.B unitex
-b classic

.B unitex
-b article -d ~/

.B unitex
-b homework -d path/to/TeX/project/

.B unitex
-v

.SH SEE ALSO
LaTeX, latexmk.
